version: "3.8"
networks:
  default:
    name: pub-sub-ingestion
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.25
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - './mysql:/docker-entrypoint-initdb.d'

  redis:
    container_name: redis
    image: redis:6.0.8
    ports:
      - '6379:6379'
#  web:
#    build:
#      dockerfile: Dockerfile
#      context: ./
#    container_name: web
#    image: faraonc/rtrust-web:${WEB_TAG:-latest}
#    environment:
#      DB_HOST: "postgres"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#
#  postgres:
#    container_name: postgres
#    image: postgres:12.7-alpine
#    volumes:
#      - ./sql:/docker-entrypoint-initdb.d
#    environment:
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "password"
#    ports:
#      - "5432:5432"
